# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{nordea-rb}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Martin Str\303\266m"]
  s.date = %q{2009-10-24}
  s.default_executable = %q{nordea}
  s.description = %q{Ruby library for accessing your Nordea Bank account and transferring money between your own accounts.}
  s.email = %q{name@my-domain.se}
  s.executables = ["nordea"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin/nordea",
     "lib/nordea.rb",
     "lib/nordea/request.rb",
     "lib/nordea/resources.rb",
     "lib/nordea/resources/account.rb",
     "lib/nordea/resources/card.rb",
     "lib/nordea/resources/fund.rb",
     "lib/nordea/resources/loan.rb",
     "lib/nordea/resources/resource.rb",
     "lib/nordea/session.rb",
     "lib/nordea/support.rb",
     "lib/nordea/transaction.rb",
     "lib/nordea/version.rb",
     "test/fixtures/account.wml",
     "test/fixtures/account_10_transactions.wml",
     "test/fixtures/account_15_transactions.wml",
     "test/fixtures/account_5_transactions.wml",
     "test/fixtures/accounts.wml",
     "test/fixtures/accounts_overview.wml",
     "test/fixtures/error.wml",
     "test/fixtures/logged_in_main_menu.wml",
     "test/fixtures/login.wml",
     "test/fixtures/transfer_to_own_account.wml",
     "test/fixtures/transfers.wml",
     "test/fixtures/transfers_1.wml",
     "test/fixtures/transfers_2.wml",
     "test/fixtures/transfers_3.wml",
     "test/test_account.rb",
     "test/test_functional.rb",
     "test/test_helper.rb",
     "test/test_nordea.rb",
     "test/test_request.rb",
     "test/test_session.rb",
     "test/test_transaction.rb"
  ]
  s.homepage = %q{http://github.com/haraldmartin/nordea-rb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby library for accessing your Nordea Bank account and transferring money between your own accounts.}
  s.test_files = [
    "test/test_account.rb",
     "test/test_functional.rb",
     "test/test_helper.rb",
     "test/test_nordea.rb",
     "test/test_request.rb",
     "test/test_session.rb",
     "test/test_transaction.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

